/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectogym;

import Principal.PagePrincipal;
import Usuario.PageUsuario;
import Servicios.PageServicios;
import Reportes.PageReportes;
import Productos.PageProductos;
import Clientes.PageClientes;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import rsbuttom.RSButtonMetro;

/**
 *
 * @author Ronal
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Pincipal1
     */
    public Menu() {
        initComponents(); 
        
        PagePrincipal p1 = new PagePrincipal();
        ShowPanel(p1);
        
        this.setLocationRelativeTo(this);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rSButtonMetro1 = new rsbuttom.RSButtonMetro();
        rSButtonMetro2 = new rsbuttom.RSButtonMetro();
        rSButtonMetro3 = new rsbuttom.RSButtonMetro();
        rSButtonMetro4 = new rsbuttom.RSButtonMetro();
        rSButtonMetro5 = new rsbuttom.RSButtonMetro();
        rSButtonMetro6 = new rsbuttom.RSButtonMetro();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        panelencabezado = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(187, 187, 187));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 449));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(10, 144, 203));
        menu.setPreferredSize(new java.awt.Dimension(115, 435));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(10, 144, 203));
        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Opciones");
        menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 47));

        jLabel2.setBackground(new java.awt.Color(10, 144, 203));
        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ventas");
        menu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 160, 47));

        rSButtonMetro1.setBackground(new java.awt.Color(10, 144, 203));
        rSButtonMetro1.setText("PRINCIPAL");
        rSButtonMetro1.setColorHover(new java.awt.Color(40, 112, 176));
        rSButtonMetro1.setColorNormal(new java.awt.Color(10, 144, 203));
        rSButtonMetro1.setColorPressed(new java.awt.Color(10, 144, 203));
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });
        menu.add(rSButtonMetro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 180, 60));

        rSButtonMetro2.setBackground(new java.awt.Color(10, 144, 203));
        rSButtonMetro2.setText("USUARIO");
        rSButtonMetro2.setColorHover(new java.awt.Color(40, 112, 176));
        rSButtonMetro2.setColorNormal(new java.awt.Color(10, 144, 203));
        rSButtonMetro2.setColorPressed(new java.awt.Color(10, 144, 203));
        rSButtonMetro2.setMaximumSize(new java.awt.Dimension(81, 17));
        rSButtonMetro2.setMinimumSize(new java.awt.Dimension(81, 17));
        rSButtonMetro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro2ActionPerformed(evt);
            }
        });
        menu.add(rSButtonMetro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 180, 60));

        rSButtonMetro3.setBackground(new java.awt.Color(10, 144, 203));
        rSButtonMetro3.setText("CLIENTES");
        rSButtonMetro3.setColorHover(new java.awt.Color(40, 112, 176));
        rSButtonMetro3.setColorNormal(new java.awt.Color(10, 144, 203));
        rSButtonMetro3.setColorPressed(new java.awt.Color(10, 144, 203));
        rSButtonMetro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro3ActionPerformed(evt);
            }
        });
        menu.add(rSButtonMetro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 180, 60));

        rSButtonMetro4.setBackground(new java.awt.Color(10, 144, 203));
        rSButtonMetro4.setText("REPORTES");
        rSButtonMetro4.setColorHover(new java.awt.Color(40, 112, 176));
        rSButtonMetro4.setColorNormal(new java.awt.Color(10, 144, 203));
        rSButtonMetro4.setColorPressed(new java.awt.Color(10, 144, 203));
        rSButtonMetro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro4ActionPerformed(evt);
            }
        });
        menu.add(rSButtonMetro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 180, 60));

        rSButtonMetro5.setBackground(new java.awt.Color(10, 144, 203));
        rSButtonMetro5.setText("SERVICIOS");
        rSButtonMetro5.setColorHover(new java.awt.Color(40, 112, 176));
        rSButtonMetro5.setColorNormal(new java.awt.Color(10, 144, 203));
        rSButtonMetro5.setColorPressed(new java.awt.Color(10, 144, 203));
        rSButtonMetro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro5ActionPerformed(evt);
            }
        });
        menu.add(rSButtonMetro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 180, 60));

        rSButtonMetro6.setBackground(new java.awt.Color(10, 144, 203));
        rSButtonMetro6.setText("PRODUCTOS");
        rSButtonMetro6.setColorHover(new java.awt.Color(40, 112, 176));
        rSButtonMetro6.setColorNormal(new java.awt.Color(10, 144, 203));
        rSButtonMetro6.setColorPressed(new java.awt.Color(10, 144, 203));
        rSButtonMetro6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro6ActionPerformed(evt);
            }
        });
        menu.add(rSButtonMetro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 180, 60));

        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 490));

        jPanel3.setBackground(new java.awt.Color(10, 144, 203));

        jLabel10.setBackground(new java.awt.Color(10, 144, 203));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("SALIR");
        jLabel10.setOpaque(true);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 180, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 86, 180, 610));

        content.setBackground(new java.awt.Color(187, 187, 187));
        content.setMinimumSize(new java.awt.Dimension(1190, 610));
        content.setName(""); // NOI18N

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 86, 1190, 610));

        panelencabezado.setBackground(new java.awt.Color(10, 144, 203));
        panelencabezado.setMinimumSize(new java.awt.Dimension(1370, 90));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesa1.png"))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(10, 144, 203));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("GYM ERIC");
        jLabel4.setOpaque(true);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesa2.png"))); // NOI18N

        javax.swing.GroupLayout panelencabezadoLayout = new javax.swing.GroupLayout(panelencabezado);
        panelencabezado.setLayout(panelencabezadoLayout);
        panelencabezadoLayout.setHorizontalGroup(
            panelencabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelencabezadoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addGap(63, 63, 63)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jLabel6)
                .addContainerGap(799, Short.MAX_VALUE))
        );
        panelencabezadoLayout.setVerticalGroup(
            panelencabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelencabezadoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelencabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(panelencabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMetro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro2ActionPerformed
        // TODO add your handling code here:
        PageUsuario p2 = new PageUsuario();
       ShowPanel(p2);
    }//GEN-LAST:event_rSButtonMetro2ActionPerformed

    private void rSButtonMetro6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro6ActionPerformed
        // TODO add your handling code here:
        PageProductos p6 = new PageProductos();
        ShowPanel(p6);
    }//GEN-LAST:event_rSButtonMetro6ActionPerformed

    private void rSButtonMetro7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMetro7ActionPerformed

    private void rSButtonMetro8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMetro8ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_jLabel10MouseClicked

    private void rSButtonMetro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro4ActionPerformed
        // TODO add your handling code here:
        PageReportes p4 = new PageReportes();
        ShowPanel(p4);
    }//GEN-LAST:event_rSButtonMetro4ActionPerformed

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        // TODO add your handling code here:
        PagePrincipal p1 = new PagePrincipal();
        ShowPanel(p1);
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void rSButtonMetro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro3ActionPerformed
        // TODO add your handling code here:
        PageClientes p3 = new PageClientes();
        ShowPanel(p3);
    }//GEN-LAST:event_rSButtonMetro3ActionPerformed

    private void rSButtonMetro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro5ActionPerformed
        // TODO add your handling code here:
        PageServicios p5 = new PageServicios();
        ShowPanel(p5);
    }//GEN-LAST:event_rSButtonMetro5ActionPerformed

    private void ShowPanel(JPanel p){
        
        p.setSize(1190, 610);
        p.setLocation(0,0);
        
        content.removeAll();
        content.add(p,BorderLayout.CENTER);
        
        content.revalidate();
        content.repaint();
        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel panelencabezado;
    private rsbuttom.RSButtonMetro rSButtonMetro1;
    private rsbuttom.RSButtonMetro rSButtonMetro2;
    private rsbuttom.RSButtonMetro rSButtonMetro3;
    private rsbuttom.RSButtonMetro rSButtonMetro4;
    private rsbuttom.RSButtonMetro rSButtonMetro5;
    private rsbuttom.RSButtonMetro rSButtonMetro6;
    // End of variables declaration//GEN-END:variables
}
